python b_policy/test.py --sim Acrobot-v1 --model_dir model_18 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_19 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_20 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_21 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_22 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_23 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_24 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_25 --expert_num 1 --data_num 0
python b_policy/test.py --sim Acrobot-v1 --model_dir model_26 --expert_num 1 --data_num 0